// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeCodeFirstApproachCrudOperation.Models;

#nullable disable

namespace PracticeCodeFirstApproachCrudOperation.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20240428184010_add-migration CodeFirstApproch")]
    partial class addmigrationCodeFirstApproch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticeCodeFirstApproachCrudOperation.Models.StudentModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Student ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Student Age");

                    b.Property<string>("Con_Password")
                        .IsRequired()
                        .HasColumnType("Varchar(100)")
                        .HasColumnName("Student Confirm Password");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("Varchar(100)")
                        .HasColumnName("Student Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(100)")
                        .HasColumnName("Student Name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("Varchar(100)")
                        .HasColumnName("Student Numer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("Varchar(100)")
                        .HasColumnName("Student Password");

                    b.HasKey("ID");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
